### ISSUE TITLE
문성준 - Todo 1st Week

### ISSUE THREAD

**Issue by moonmisae118** [defee-project/defee-frontend#1]

**Comment by moonmisae118** [comment]
- [x] 헤드라인 페이지
  - [x] 카테고리 구현
  - [x] 인기 게시글 구현
    - [x] 게시글 위젯 분리
  - [x] 포스트 컨텐츠 구현
      - [x] 게시글 슬라이드 구현
  - [x] 다른 포스트 구현

- [x] 헤더 바
  - [x] UI 구현

- [x] 푸터 바
  - [x] UI 구현 
  - [x] 카테고리 구현
  - [x] 버튼 이벤트 구현
  - [x] 라우터 연결 구현
