### ISSUE TITLE
문성준 - Todo 3rd~4nd Week

### ISSUE THREAD

**Issue by moonmisae118** [defee-project/defee-frontend#19]
- [x] 헤더
  - [x] 텍스트 동적 표시
  - [x] 뒤로가기 삭제

- [x] 회원가입
  - [x] 수정된 UI 구현 
  - [x] 코드 입력창 추가
  - [x] 이메일 인증 버튼 클릭 시 코드 입력창 생성
  - [x] 정규식 검사
  - [x] 회원가입 버튼 유효성 검사

- [x] 포스트 위젯 공용 컴포넌트 분류 name : gallary_view_post.dart

- [x] 추천 페이지 UI 구현
