### ISSUE TITLE
이시현 - Todo 1st Week

### ISSUE THREAD

**Issue by pongpongie** [defee-project/defee-frontend#2]

**Comment by pongpongie** [comment]
# To do
- [x] 프로젝트 환경 세팅
- [x] Log In, Log Out Page design
- [x] Settings Page design
- [x] Post Page design

## Page
**Post 페이지**
- Tool Bar
  - [x] Share BTN
    - [x] Share Modal
  - [x] AI summation BTN
  - [x] Scrape BTN
    - [x] Scrape Modal, onPress()
  - [x] Exit BTN
  - [x] Address Bar
    - [x] onPress()
- Nav Bar
  - [x] go back BTN
  - [x] go forward BTN
  - [x] refresh BTN
- Post View
  - [x] WebView
