### ISSUE TITLE
이시현 - Todo 3rd~4nd Week

### ISSUE THREAD

**Issue by pongpongie** [defee-project/defee-frontend#22]
# Main Task
## `setting` page
- [x] 위젯 설계
- [x] 위젯 UI 구현

## `login` page
- [x] dio 활용한 api 설계
- [x] api 구현

# Sub Task
- [x] api 통신 알아보기, 일반적으로 서버와 어떻게 통신하는지
- [ ] `post` 스크롤 이벤트 구현
## figma 정리
- [x] 그룹화
- [x] color variable 정리
- [x] section 나누기

--- 

추후 더 추가 예정
