### ISSUE TITLE
전인우 - Todo 4th Week

### ISSUE THREAD

**Issue by Indwoo** [defee-project/defee-frontend#26]
<h1> Main Tasks </h1>

- [x] 검색 페이지 -> 검색 결과 페이지 이동 구현
- [x] 검색 API 명세

<h1> Sub Tasks </h1>

- [x] 필요 API 명세
